services:
  - type: web
    name: production-ai-agent
    runtime: docker
    rootDir: 06-lab-complete
    region: singapore
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: APP_VERSION
        value: "1.0.0"
      - key: LLM_MODEL
        value: mock
      - key: AGENT_API_KEY
        generateValue: true
      - key: RATE_LIMIT_PER_MINUTE
        value: "10"
      - key: MONTHLY_BUDGET_USD
        value: "10.0"
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: production-ai-agent-redis
          property: connectionString

  - type: keyvalue
    name: production-ai-agent-redis
    region: singapore
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru
